[workspace]
members = [
    "iroh",
    "iroh-blobs",
    "iroh-base",
    "iroh-dns-server",
    "iroh-gossip",
    "iroh-metrics",
    "iroh-net",
    "iroh-docs",
    "iroh-test",
    "iroh-net/bench",
    "iroh-cli",
    "iroh-willow",
]
resolver = "2"

[profile.release]
debug = true

[profile.bench]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[profile.dev.package]
# optimize crypto dependencies in dev mode
ed25519-dalek = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
iroh-blake3 = { opt-level = 3 }

[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unused-async = "warn"

[patch.crates-io]
# willow-data-model = { path = "../willow-rs/data-model" }
# willow-encoding = { path = "../willow-rs/encoding" }
# meadowcap = { path = "../willow-rs/meadowcap" }
willow-data-model = { git = "https://github.com/n0-computer/willow-rs.git", branch = "iroh-dev" }
willow-encoding  = { git = "https://github.com/n0-computer/willow-rs.git", branch = "iroh-dev" }
meadowcap  = { git = "https://github.com/n0-computer/willow-rs.git", branch = "iroh-dev" }
